### ISSUE TITLE
Enhancement Request: Ubuntu Boxes!

### ISSUE THREAD

**Issue by clayg** [naveenrajm7/vagrant_utm#2]
We're excited to try this out!  Our team mostly uses Linux+VirtualBox, but a few people are into Macs (for some reason :wink:) and have been forced to use Parallels Pro with vagrant.

I noticed the public hashicorp box catalog doesn't have a filter for utm yet:

https://portal.cloud.hashicorp.com/vagrant/discover?architectures=arm64&query=ubuntu

It sounds like using your utm-packer plugin would be the best wasy to get started with a box for testing vagrant_utm with ubuntu:

https://github.com/naveenrajm7/packer-plugin-utm

... or test the waters with one of the existing debian boxes:

https://naveenrajm7.github.io/vagrant_utm/boxes/utm_box_gallery.html

Thanks for sharing!

**Comment by naveenrajm7** [comment]
Hello!

I am very happy that you are trying this out.

Yes, we currently do not support Vagrant Boxes because UTM does not support import yet https://github.com/utmapp/UTM/issues/6612.

Once it's available, we will add support for Vagrant boxes.
Then we can publish some popular boxes in Vagrant Cloud (or now  HCP Vagrant Registry).

Till then we are limited to using UTM files.

**Comment by naveenrajm7** [comment]
Hello , 

I am happy to share that we now have an Ubuntu box in the HCP vagrant registry. 
https://portal.cloud.hashicorp.com/vagrant/discover/utm/ubuntu-24.04 
> I will caution that is box is around 2 GB

I have also updated the plugin to support Vagrant boxes, if you have already installed the plugin please update to the latest beta release and give it a try

```bash
# update plugin
vagrant plugin update vagrant_utm
# Init
vagrant init utm/ubuntu-24.04
# Start
vagrant up
```

Thanks for trying the plugin!
