### ISSUE TITLE
ArgumentError, "all arguments must be String: #{args.inspect}"

### ISSUE THREAD

**Issue by SeanSith** [naveenrajm7/vagrant_utm#8]
**Describe the bug**

ArgumentError when performing `vagrant up`

### Debug output
https://gist.github.com/SeanSith/707dd63c162a9cf8ded232c238fa0711

### Expected behavior

Expected a working Ubuntu 24.04 install from the vagrant UTM box

#### Setup
```bash
brew install vagrant
brew install --cask utm
vagrant plugin install vagrant_utm
vagrant init utm/ubuntu-24.04
# Vagrant here downloads the box successfully
vagrant up
```

At this point UTM opens, asks to import the box from the ~/.vagrant.d directory. Box does not import, leaving UTM without a VM. Additionally, vagrant does not wait for the import and fails at the console with the debug output above.

### Reproduction information

**Versions (please complete the following information):**:

- Operating system: macOS 15.1.1 (M3 Pro, 2023)
- UTM version [As seen in `About UTM`]: 4.5.4 (100) (from Homebrew)
- Vagrant version [output of `vagrant version`]: 2.4.3
- Vagrant flavour [Upstream or Distro]: from Homebrew, guessing upstream?
- Vagrant plugins versions (including vagrant_utm) [output of `vagrant plugin list`]: vagrant_utm (0.1.0, global)

#### Vagrantfile
From `vagrant init utm/ubuntu-24.04` (with comments removed):

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "utm/ubuntu-24.04"
end
```

**Comment by naveenrajm7** [comment]
Hi 
Thank you for trying 0.1.0 (beta) version of the plugin. 

Unfortunately, version 0.1.0+ will only support UTM versions 4.6.x (non-beta)

Please use plugin version 0.0.1 if you want to work with UTM 4.5.x

This is because current plugin version has made a significant change on how VMs are imported. It now uses vagrant box format.
We were able to add corresponding import support in UTM which is available from UTM version 4.6.x only.

I will fix this issue by adding better error message on supported UTM versions for a given plugin version.

Thanks for detailed bug report.
